#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/jenkins

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Download Jenkins Keyring
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins Repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
